FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    python3-pip python3-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.bot.txt .
RUN pip install --no-cache-dir -r requirements.bot.txt -vvv

COPY bot.py .
COPY functions.py .
ENV CUDA_DEVICE_ORDER=PCI_BUS_ID
ENV VLLM_USE_V1=0
CMD ["python3", "bot.py"]