version: '3.8'

services:
  llm_front:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: llm_front
    env_file:
      - .env
    volumes:
      - ./data:/app/data

  llm_back:
    build:
      context: .
      dockerfile: Dockerfile.llm
    container_name: llm_back
    env_file:
      - .env
    environment:
      - CUDA_DEVICE_ORDER=PCI_BUS_ID
      - CUDA_VISIBLE_DEVICES=1 # Используем только GPU 1 (RTX 4070 Ti)
      - PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True  # Оптимизация памяти
    ports:
      - "8844:8844"  # Для отладки
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']  # Явно указываем GPU 1
              capabilities: [gpu]